find_path(CHIPMUNK_INCLUDE_DIR chipmunk/chipmunk.h)
find_library(CHIPMUNK_LIBRARY NAMES chipmunk)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CHIPMUNK DEFAULT_MSG CHIPMUNK_LIBRARY CHIPMUNK_INCLUDE_DIR)

MARK_AS_ADVANCED(
  CHIPMUNK_INCLUDE_DIR
  CHIPMUNK_LIBRARY
)
