find_path(TURBOBADGER_INCLUDE_DIR tb/tb_core.h)
find_library(TURBOBADGER_LIBRARY NAMES TurboBadgerLib)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TURBOBADGER DEFAULT_MSG TURBOBADGER_LIBRARY TURBOBADGER_INCLUDE_DIR)

MARK_AS_ADVANCED(
  TURBOBADGER_INCLUDE_DIR
  TURBOBADGER_LIBRARY
)
